package com.example.recyclerview;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        RecyclerView recyclerView = findViewById(R.id.recyclerview);


        List<Item> items = new ArrayList<Item>();
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));

        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));
        items.add(new Item("Chung kết World Cup 2022 'hay nhất lịch sử'","\"Trận đấu này là minh chứng cho thấy tại sao bóng đá là môn thể thao hấp dẫn nhất hành tinh\", Keane nói trên Sky Sports tối 18/12. \"Một trận đấu tuyệt vời, đầy mê hoặc và căng thẳng. Có những khoảnh khắc sống động, khao khát và dũng cảm\".\n" +
                "\n" +
                "Cựu tiền vệ Man Utd cũng cho rằng vì lý do này, Argentina xứng đáng với chức vô địch khi giữ vững tinh thần dù phải vượt qua đối thủ ba lần, gồm việc bị gỡ hòa 2-2 dù dẫn hai bàn trong hai hiệp chính, bị gỡ hòa 3-3 trong hiệp phụ thứ hai và loạt luân lưu - nơi Pháp được đá trước. Keane nhận xét sự căng thẳng của trận đấu đã đẩy áp lực trên vai Lionel Messi lên đến đỉnh điểm, để rồi anh tự đưa bản thân vượt qua giới hạn. \"Cậu ấy sẽ mất nhiều tuần, thậm chí nhiều tháng để hồi phục. Nhưng đây là cái kết quá tuyệt vời cho Messi\", ông nói.",R.drawable.a));




        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(new MyAdapter(getApplicationContext(),items));
    }

}